name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thank you for creating the issue, please ensure that you have completed all sections of the template.'
        pr-message: 'Thanks for opening this PR, members of the @niftools-blender-addon-reviewers team will review it shortly'
